/**
 * Default recipe values for the Living Grass experience.
 *
 * This is the canonical default state for the organic-simulation effect class.
 * It is also the reference template for any shader-based organic simulation.
 */

import type { ShaderParamsRecipe } from "./types";

export const LIVING_GRASS_DEFAULT_RECIPE: ShaderParamsRecipe = {
  schemaVersion: "1",
  effectClass: "organic-simulation",
  mutationTransition: "8s",
  shaderStack: [
    "grass-field",
    "wind-distortion",
    "color-grade",
    "depth-parallax",
    "feedback-subtle",
  ],
  parameters: {
    grassDensity: {
      label: "Grass Density",
      value: 0.6,
      min: 0.1,
      max: 1.0,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.2, max: 0.9 },
      ui: true,
    },
    bladeHeight: {
      label: "Blade Height",
      value: 0.55,
      min: 0.2,
      max: 0.85,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.35, max: 0.75 },
      ui: true,
    },
    windStrength: {
      label: "Wind Strength",
      value: 0.4,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.05, max: 0.85 },
      ui: true,
    },
    windDirection: {
      label: "Wind Direction",
      value: 0.5,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.1, max: 0.9 },
      ui: false,
    },
    windTurbulence: {
      label: "Turbulence",
      value: 0.3,
      min: 0.0,
      max: 0.8,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.05, max: 0.65 },
      ui: true,
    },
    growthSpeed: {
      label: "Growth Speed",
      value: 0.3,
      min: 0.02,
      max: 0.8,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.05, max: 0.6 },
      ui: true,
    },
    colorTemperature: {
      label: "Color Temperature",
      value: 0.5,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.15, max: 0.85 },
      ui: true,
    },
    colorSaturation: {
      label: "Color Saturation",
      value: 0.7,
      min: 0.2,
      max: 1.0,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.35, max: 0.9 },
      ui: true,
    },
    groundFogDensity: {
      label: "Ground Fog",
      value: 0.2,
      min: 0.0,
      max: 0.6,
      step: 0.01,
      randomizable: true,
      artistBounds: { min: 0.0, max: 0.5 },
      ui: true,
    },
    breathingAmplitude: {
      label: null,
      value: 0.15,
      min: 0.0,
      max: 0.4,
      step: 0.005,
      randomizable: false,
      ui: false,
    },
    feedbackDecay: {
      label: null,
      value: 0.88,
      min: 0.7,
      max: 0.98,
      step: 0.005,
      randomizable: false,
      ui: false,
    },
    nightModeIntensity: {
      label: null,
      value: 0.0,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      randomizable: false,
      ui: false,
    },
  },
  signalBindings: {
    "audio.level": {
      target: "windStrength",
      curve: "ease-out",
      inputRange: [0.0, 1.0],
      outputRange: [0.05, 0.85],
      smoothing: "0.3s",
    },
    proximity: {
      target: "grassDensity",
      curve: "linear",
      inputRange: [0.0, 1.0],
      outputRange: [0.3, 0.85],
      smoothing: "1.5s",
    },
    cameraMotion: {
      target: "windDirection",
      curve: "linear",
      inputRange: [0.0, 1.0],
      outputRange: [0.2, 0.8],
      smoothing: "2.0s",
    },
  },
};
