import { isBuiltinShaderHiddenFromLibrary } from "./hiddenBuiltinShaders";
import type { ShaderExtensionDefinition } from "@artex/extensions";

const stripGlslComments = (source: string): string => {
  const noBlocks = source.replace(/\/\*[\s\S]*?\*\//g, (match) => match.replace(/[^\n]/g, " "));
  return noBlocks.replace(/\/\/[^\n]*/g, "");
};

export interface BuiltinShaderLibraryCapabilities {
  usesAudio: boolean;
  usesCamera: boolean;
  usesProximity: boolean;
  usesChannels: boolean;
  usesFlow: boolean;
  usesStates: boolean;
}

export interface BuiltinShaderLibraryItem {
  id: string;
  label: string;
  filename: string;
  description: string;
  tags: string[];
  capabilities: BuiltinShaderLibraryCapabilities;
  source: string;
  /**
   * URL of a pre-baked static thumbnail (a single rendered frame), committed
   * under `./thumbnails/<id>.webp` and generated by
   * `scripts/bake_shader_thumbnails.mjs`. Present for every shader that renders
   * in the standalone thumbnail context; absent for V3-compositor / state
   * shaders that can't (those fall back to live generation in the catalog).
   * Baking these once means the catalog loads them as plain images instead of
   * compiling ~40 shaders in every visitor's browser (issue #1408).
   */
  thumbnailUrl?: string;
  /**
   * NOTE: the credit deliberately does NOT live here. `getBuiltinShaderAuthorship(id)`
   * in `./builtinShaderAuthorship` is the lookup, called by the two surfaces that
   * render one.
   *
   * It was a field on this interface for one round and cost ~1.2KB brotli on
   * every artwork-playback route in the app: this registry is what a route
   * resolves a shader's SOURCE from, so a value import of the credit data put
   * attribution prose into 19 closures that render none of it. A shader's
   * bytes and a shader's byline have different consumers, and the type is
   * where that stops being true if they are merged.
   */
}

interface BuiltinShaderLibraryMetadata {
  label?: string;
  description: string;
}

const SHADER_SOURCE_EXTENSION = /\.(glsl|frag)$/i;

const BUILTIN_SHADER_SOURCES: Record<string, string> = import.meta.glob("./shaders/*", {
  eager: true,
  query: "?raw",
  import: "default",
});

// Pre-baked static thumbnails (one rendered frame per shader), keyed by shader
// id. Generated by scripts/bake_shader_thumbnails.mjs and committed alongside
// the sources; bundled as hashed asset URLs by the consuming Vite build. Empty
// on a checkout that hasn't baked yet — shaders then fall back to live thumbnail
// generation in the catalog.
const BUILTIN_SHADER_THUMBNAIL_URLS: Record<string, string> = import.meta.glob(
  "./thumbnails/*.webp",
  { eager: true, query: "?url", import: "default" },
);

const BUILTIN_SHADER_THUMBNAIL_BY_ID: Record<string, string> = Object.fromEntries(
  Object.entries(BUILTIN_SHADER_THUMBNAIL_URLS).map(([assetPath, url]) => {
    const file = assetPath.split("/").pop() ?? assetPath;
    return [file.replace(/\.webp$/i, ""), url];
  }),
);

const BUILTIN_SHADER_LIBRARY_METADATA: Partial<Record<string, BuiltinShaderLibraryMetadata>> = {
  "artex-living-field": {
    label: "ARTEX Living Field",
    description: "Living light / living matter field with slow memory and presence-driven deformation.",
  },
  "anemone-dustfield-artex": {
    description: "Blue cup blooms with sparkling pollen dust.",
  },
  "bumped-sinusoidal-warp-artex": {
    description: "ARTEX-compatible bumped sine warp shader.",
  },
  "cobalt-petal-plume-artex": {
    description: "Luminous cobalt flower plume with particle spray.",
  },
  "comic-wall-mosaic-artex": {
    description: "Pinned comic board mosaic with sketchy marker panels.",
  },
  "ghost-flora-column-artex": {
    description: "Translucent flora cluster with coral filament column.",
  },
  "gif-tile-dancer-grid-artex": {
    description: "GIF-inspired tiled dancer wall with per-cell motion and silhouette edge glow.",
  },
  "golden-electric-spiral-artex": {
    description: "Golden electric spiral that distorts the artwork with pulsing arcs and radial grid patterns.",
  },
  "golden-porous-rift-artex": {
    description: "Molten porous cavern with glowing golden ridges.",
  },
  "kesson-fbm-image-distortion-artex": {
    description: "ARTEX-compatible FBM distortion shader.",
  },
  "kesson-image-extrusion-1-artex": {
    description: "ARTEX-compatible image extrusion shader (variant 1).",
  },
  "kesson-image-extrusion-2-artex": {
    description: "ARTEX-compatible image extrusion shader (variant 2).",
  },
  "kesson-image-extrusion-3-artex": {
    description: "ARTEX-compatible image extrusion shader (variant 3).",
  },
  "kesson-kifs-fractal-artex": {
    description: "ARTEX-compatible KIFS fractal shader.",
  },
  "kirby-jump-artex": {
    description: "ARTEX-compatible Kirby jump shader.",
  },
  "lavender-poppy-veils-artex": {
    description: "Large translucent lavender poppy veils with orange buds.",
  },
  "lupine-apparition-artex": {
    description: "Central lupine-like spike with layered ghost petals.",
  },
  "filament-column-artex": {
    description: "Dense luminous ribbon column with reactive filaments.",
  },
  "flower-sdf-artex": {
    label: "Flower SDF ARTEX",
    description: "Procedural rose-curve flower that opens with proximity and sways with audio.",
  },
  "masterpiece-mesh-artex": {
    label: "Mesh A - Continuous Column",
    description: "Version A. Keep the artwork as one continuous moving column inside the filament structure.",
  },
  "matrix-op-artex": {
    description: "Menger fractal geometry that distorts and tints the artwork through recursive 3D structure.",
  },
  "moon-surface-ii-artex": {
    description: "Lunar terrain that sculpts the artwork with FBM-driven topography and depth lighting.",
  },
  "neon-botanical-filaments-artex": {
    description: "Generative translucent wireframe flower field.",
  },
  "particula-artex": {
    description: "Audio-reactive particle spheres: magenta/pink inner cloud + purple/cyan outer shell, with orbiting sparks. Beat transients pulse the radius outward.",
  },
  "pastel-wave-trails-artex": {
    description: "Layered pastel wave ribbons with drifting shimmer and face-driven pull.",
  },
  "phone-chromatic-warp-artex": {
    label: "Phone Chromatic Warp",
    description: "Polar swirl with per-channel chromatic split. Designed as a trigger shader for the 'holding a phone' gesture.",
  },
  "phone-glitch-split-artex": {
    label: "Phone Glitch Split",
    description: "RGB split, scanline tear, and pixel noise. Designed as a trigger shader for the 'holding a phone' gesture.",
  },
  "primitive-intelligence-study-artex": {
    description: "Near-black synthetic face study with reactive iris, harmonic shell, and sparse telemetry dust.",
  },
  "reactive-compute-splat-bloom-artex": {
    description: "Floating translucent particle veil with white micro-sparks and curl-like drift.",
  },
  "reeded-glass-portrait-artex": {
    description: "Portrait viewed through vertical fluted glass — face refracts into amber ribs with black drips, reactive to face, audio, and proximity.",
  },
  "sixteen-segment-display-v4-artex": {
    description: "Neon 16-segment LED text overlaid on the artwork, reactive to audio and proximity.",
  },
  "sonic-lens-dual-lens-artex": {
    label: "Sonic Lens Dual Lens",
    description: "Two corner-anchored triangular lenses: left shows left/right symmetry heat, right shows color-diversity on a hue wheel. Proximity-breathed with a gold hypotenuse seam.",
  },
  "station-17-artex": {
    description: "ARTEX-compatible STATION 17 shader.",
  },
  "kesson-voyage": {
    label: "Kesson Voyage",
    description: "Gyroid tunnel that warps the artwork through twisting organic corridors with glowing beam accents.",
  },
  "verdant-synapse-web-artex": {
    description: "Green synaptic membrane network with bright nodes.",
  },
};

const stripShaderExtension = (filename: string): string => filename.replace(SHADER_SOURCE_EXTENSION, "");

const toShaderSlug = (value: string): string =>
  value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

const toShaderLabel = (baseName: string): string => {
  const normalized = baseName
    .replace(/[_-]+/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/([A-Za-z])(\d)/g, "$1 $2")
    .replace(/\s+/g, " ")
    .trim();

  if (!normalized) return "Unnamed shader";
  return normalized.charAt(0).toUpperCase() + normalized.slice(1);
};

const inferBuiltinShaderCapabilities = (source: string): BuiltinShaderLibraryCapabilities => {
  const lowerSource = stripGlslComments(source).toLowerCase();
  const hasAny = (tokens: string[]) => tokens.some((token) => lowerSource.includes(token.toLowerCase()));
  return {
    usesAudio: hasAny(["uAudioLevel", "uBassLevel"]),
    usesCamera: hasAny(["uCameraLevel"]),
    usesProximity: hasAny(["uProximity"]),
    usesChannels: hasAny(["iChannel0", "iChannel1", "iChannel2", "iChannel3", "uMask", "uState1", "uState2"]),
    usesFlow: hasAny(["uFlowEnabled", "uFlowIntensity", "uFlowSpeed", "uFlowScale"]),
    usesStates: hasAny(["uUseStateBlending", "uStateA", "uStateB", "uStateC", "uStateD"]),
  };
};

const getBuiltinShaderCapabilityTags = (capabilities: BuiltinShaderLibraryCapabilities): string[] => {
  const tags: string[] = [];
  if (capabilities.usesAudio) tags.push("Audio");
  if (capabilities.usesCamera) tags.push("Camera");
  if (capabilities.usesProximity) tags.push("Proximity");
  if (capabilities.usesChannels) tags.push("Channels");
  if (capabilities.usesFlow) tags.push("Flow");
  if (capabilities.usesStates) tags.push("States");
  if (tags.length === 0) tags.push("Simple");
  return tags;
};

/**
 * REGISTERED shaders — every built-in the package ships, including ones that
 * are not offered for freeform picking. Resolvers (experiences that name a
 * shader id, the Studio's apply path) must read this: hiding a shader from
 * the browse list must never make it unresolvable, or the experiences that
 * reference it break.
 */
export const BUILTIN_SHADER_REGISTRY: BuiltinShaderLibraryItem[] = Object.entries(BUILTIN_SHADER_SOURCES)
  .filter(([path]) => SHADER_SOURCE_EXTENSION.test(path))
  .map(([path, source]) => {
    const filename = path.split("/").pop() ?? path;
    const baseName = stripShaderExtension(filename);
    const id = toShaderSlug(baseName);
    const metadata = BUILTIN_SHADER_LIBRARY_METADATA[id];
    const capabilities = inferBuiltinShaderCapabilities(source);
    const isGeneratedMotionShader = /-motion-\d+-artex$/.test(id);

    return {
      id,
      label: metadata?.label ?? toShaderLabel(baseName),
      filename,
      description: metadata?.description
        ?? (isGeneratedMotionShader
          ? "Video-converted motion shader with seeded palette and rhythm."
          : "Built-in ARTEX shader."),
      tags: getBuiltinShaderCapabilityTags(capabilities),
      capabilities,
      source,
      thumbnailUrl: BUILTIN_SHADER_THUMBNAIL_BY_ID[id],
    };
  })
  .sort((a, b) => a.label.localeCompare(b.label, undefined, { sensitivity: "base" }));

/**
 * OFFERED shaders — what a browse UI lists. Pipeline shaders (an experience's
 * own field, a compositor diagnostic) are registered but not offered.
 */
export const BUILTIN_SHADER_LIBRARY_ITEMS: BuiltinShaderLibraryItem[] = BUILTIN_SHADER_REGISTRY
  .filter((shader) => !isBuiltinShaderHiddenFromLibrary(shader.id));

export const createBuiltinShaderExtensionDefinitions = (): ShaderExtensionDefinition[] => (
  BUILTIN_SHADER_REGISTRY.map((shader) => ({
    id: shader.id,
    kind: "shader",
    label: shader.label,
    source: shader.source,
    tags: [...shader.tags],
    capabilities: ["shader:register"],
  }))
);
